package ch.hevs.businessobject;

import java.io.Serializable;

import javax.persistence.CascadeType;
import javax.persistence.Embeddable;
import javax.persistence.ManyToOne;

//@Embeddable
public class UserAnimeId implements Serializable{
//	Old version with join table and supp element
	
//	//Relations
//	private User user;
//	private Anime anime;
//	
//	//User
//	@ManyToOne(cascade = CascadeType.ALL)
//	public User getUser() {
//		return user;
//	}
//	
//	public void setUser(User user) {
//		this.user = user;
//	}
//
//	//Anime
//	@ManyToOne(cascade = CascadeType.ALL)
//	public Anime getAnime() {
//		return anime;
//	}
//	public void setAnime(Anime anime) {
//		this.anime = anime;
//	}
	
	//AutoGenerated HashCode
//		@Override
//		public int hashCode() {
//			final int prime = 31;
//			int result = 1;
//			result = prime * result + ((anime == null) ? 0 : anime.hashCode());
//			result = prime * result + ((user == null) ? 0 : user.hashCode());
//			return result;
//		}

//    public int hashCode() {
//        int result;
//        result = (anime != null ? anime.hashCode() : 0);
//        result = 31 * result + (user != null ? user.hashCode() : 0);
//        return result;
//    }

	//AutoGenerated Equals
//	@Override
//	public boolean equals(Object obj) {
//		if (this == obj)
//			return true;
//		if (obj == null)
//			return false;
//		if (getClass() != obj.getClass())
//			return false;
//		UserAnimeId other = (UserAnimeId) obj;
//		if (anime == null) {
//			if (other.anime != null)
//				return false;
//		} else if (!anime.equals(other.anime))
//			return false;
//		if (user == null) {
//			if (other.user != null)
//				return false;
//		} else if (!user.equals(other.user))
//			return false;
//		return true;
//	}
	
	
//	public boolean equals(Object o) {
//        if (this == o) return true;
//        if (o == null || getClass() != o.getClass()) return false;
//
//        UserAnimeId that = (UserAnimeId) o;
//
//        if (anime != null ? !anime.equals(that.anime) : that.anime != null) return false;
//        if (user != null ? !user.equals(that.user) : that.user != null)
//            return false;
//
//        return true;
//    }
	
}